### PR TITLE
added slider, optiondialog, and switch

### PR DESCRIPTION
**Pull request by Sophrinix**
still testing this, but this should work.

Is this the right way to add new functionality, or do you want to eventually split these register functions off into their own file?

### CODE REVIEW

**Comment by Sophrinix** [comment]
Also, how do you want to handle platform specific things like an ActionBar or a NavigationWindow?

**Comment by yuchi** [comment]
Thank you! Merged!

> Is this the right way to add new functionality

Currently, it is.

> do you want to eventually split these register functions off into their own file?

This will happen only for managed components. See the next one…

> Also, how do you want to handle platform specific things like an ActionBar or a NavigationWindow?

This is going to be a lot of fun! We have the following fragile components:
- Top Level
  - `NavigationWindow`
  - `SplitWindow`
  - `TabGroup`/`Tab`
- Custom children
  - `ScrollableView` (uses `.views` property instead of `.add()`)
  - `ListView` (templates, sections, `section.items`…)

And probably others

**Comment by Sophrinix** [comment]
We might want to consider using the Ti namespace instead of the Titanium namespace. Mostly due to trademark issue around the word Titanium. Also if a fork were to happen, it would be future proof :-)

**Comment by yuchi** [comment]
Well, given that:

``` js
assert( Ti.UI.createView({}).apiName === 'Ti.UI.View' );
```

you’re definitely right.

Let’s switch both the calls (in the factories) and in the explicit names.

**Pull request merged**
