### PR TITLE
Fixed broken react-blessed link in README

### PR DESCRIPTION
**Pull request by elazar**

### CODE REVIEW

**Comment by yuchi** [comment]
Whoops! Thanks!

**Comment by yuchi** [comment]
Could you use the bracket notation instead of the inline one?

**Comment by elazar** [comment]
Sorry, not sure what notation you're referring to.

**Comment by yuchi** [comment]
[This one](https://github.com/yuchi/react-titanium/commit/17ba7b510b270446cfb157b1ecd8d953e98791b7#diff-04c6e90faac2675aa89e2176d2eec7d8R101) :)

Thank you anyway!

**Pull request closed without merging**
